import React from "react";
import NftLayout from "@components/Layout/NftLayout";
import {
  Stack,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from "@chakra-ui/react";
import { Markup } from "interweave";
import { useEffect } from "react";

function LegalPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <NftLayout>
      <Stack bg="#181818" mx="auto" maxW="container.md" my={8} p={8}>
        <Tabs>
          <TabList>
            {tabData.map((tab, index) => (
              <Tab key={index}>{tab.label}</Tab>
            ))}
          </TabList>

          <TabPanels>
            {tabData.map((tab, index) => (
              <TabPanel p={4} key={index}>
                <Markup content={tab.content} />
              </TabPanel>
            ))}
          </TabPanels>
        </Tabs>
      </Stack>
    </NftLayout>
  );
}

export default LegalPage;

const tabData = [
  {
    label: "Terms of Service",
    content: `<p>Welcome to ArtZero – an NFT Marketplace in the Aleph Zero network.</p>

    <p><br>
     </p>
    
    <p>The website www.artzero.io ("artzero.io") is owned and operated by ArtZero Ltd., Co ("ArtZero" or "us" or "we" or "our"), having its registered office located BIDV Building, 7th Floor, 37 Nguyen Son st., Ngoc Lam ward, Long Bien district, Hanoi city, Vietnam. </p>
    
    <p><br>
     </p>
    
    <p>Please read the Terms of Service document carefully before using the Artzero.io website. By using the Artzero.io website, you signify your agreement to be bound by Artzero's Terms of Service. In addition, when you use any current or future Artzero.io service (eg. Launchpad or Marketplace) ("Artzero Service"), you will also be subject to the terms, guidelines and conditions applicable to that Artzero Service. ("Terms"). If these Terms of Service are inconsistent with such Terms, the Terms will control.</p>
    
    <p><br>
     </p>
    
    <p>These "Terms of Service" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
    
    <p>- Conditions Relating to Your Use of Artzero.io</p>
    
    <p>- Notice and Procedure for Making Claims of Infringement</p>
    
    <p>- Notice and Procedure for Notifying Artzero.io of Objectionable Content</p>
    
    <p><br>
     </p>
    
    <p>These Terms of Service govern your access to and use of the ArtZero website(s), our APIs, mobile app (the “App”), and any other software, tools, features, or functionalities provided on or in connection with our services; including without limitation using our services to view, explore, and create NFTs and use our tools, at your own discretion, to connect directly with others to purchase, make bid, sell, or transfer NFTs on public blockchains (collectively, the “Service”)</p>
    
    <p><br>
     </p>
    
    <p>As described in our Privacy Notice, we do not share information with any individuals, organizations or any third-party service providers. For any further details on our security practices please read our Privacy Notice. For any queries or issues relating to Artzero.io, you can contact us by clicking <a href="http://www.artzero.io/contact-us">www.Artzero.io/contact-us</a> </p>
    
    <p><br>
     </p>
    
    <p>We require all users to be at least 18 years old. If you are under 18 years old, you are prohibited to use ArtZero even through a parent or guardian’s Account and with their approval and oversight. </p>
    
    <p><strong>1. Your Account</strong></p>
    
    <p>On ArtZero, like other web3 or web 3.0, your blockchain address functions as your identity. Accordingly, you will need a blockchain address and a third-party wallet to access the Service. Your account on the service (“Account”) will be associated with your blockchain address; however, if you want to add some additional information, such as a profile picture, you can add it to your Account.</p>
    
    <p><br>
    </p>
    
    <p>If your Account becomes inactive for six months or longer, as determined by ArtZero in its sole discretion, you understand that ArtZero may disable your Account or reassign your username or associated url.</p>
    
    <p><br>
    </p>
    
    <p>ArtZero may require you to provide additional information and documents in certain circumstances, such as at the request of any government authority, as any applicable law or regulation dictates, or to investigate a potential violation of these Terms of Service. In such cases, ArtZero, in its sole discretion, may disable your Account and block your ability to access the Service until such additional information and documents are processed by ArtZero. If you do not provide complete and accurate information in response to such a request, ArtZero may refuse to restore your access to the Service.</p>
    
    <p><br>
     </p>
    
    <p><strong>2. Access to ArtZero</strong></p>
    
    <p>Your Account on ArtZero will be associated with your linked blockchain address and display the NFTs for that blockchain address (and, if applicable, any content associated with such NFTs). The blockchain address can be from Subwallet, Polkadot js., or any third-party wallet providers in the future. By using your wallet in connection with the Service, you agree that you are using that wallet under the terms and conditions of the applicable provider of the wallet. Wallets are not operated by, maintained by, or affiliated with ArtZero, and ArtZero does not have custody or control over the contents of your wallet and has no ability to retrieve or transfer its contents. ArtZero accepts no responsibility for, or liability to you, in connection with your use of a wallet and makes no representations or warranties regarding how the Service will operate with any specific wallet. </p>
    
    <p><br>
     </p>
    
    <p><strong>3. Security</strong></p>
    
    <p>You are solely responsible for keeping your wallet secure and you should never share your wallet credentials or seed phrase with anyone and for restricting access to your computer to prevent unauthorised access to your account. If you discover an issue related to your wallet, please contact your wallet provider. You agree to accept sole responsibility for all activities that occur under your account and any associated wallet and we are not liable for any acts or omissions by you in connection with your Account or as a result of your Account or wallet being compromised. You agree to immediately notify us if you discover or otherwise suspect any security issues related to the Service or your Account (you can contact us here <a href="http://www.artzero.io/contact-us">www.Artzero.io/contact-us</a>).</p>
    
    <p><br>
    </p>
    
    <p>ArtZero does not store any password or seed phrase, nor has any access to any User credentials, except the User’s address email when a User willingly decided to subscribe or share it with Solanart, and therefore cannot be held liable for any security breach attributed to a User. </p>
    
    <p><br>
     </p>
    
    <p><strong>4. Unauthorised Access </strong></p>
    
    <p>You also represent and warrant that you will comply with all applicable laws (e.g., local, state, federal and other laws) when using the Service. Without limiting the foregoing, by using the Service, you represent and warrant that: </p>
    
    <p><br>
    </p>
    
    <p>(a) you are not located in, ordinarily resident in, or organized under the laws of any jurisdiction that is subject to a comprehensive U.S. Government embargo ("Embargoed Jurisdiction"); </p>
    
    <p><br>
    </p>
    
    <p>(b) you are not subject to any sanctions, prohibition or administered by an agency of the U.S. Government, any other government, or the United Nations (collectively, “Sanctions”); </p>
    
    <p><br>
    </p>
    
    <p>(c) you are not owned or controlled, directly or indirectly, by any person that is subject to Sanctions, or that is located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction; </p>
    
    <p><br>
    </p>
    
    <p>(d) none of your officers, managers, directors, shareholders or authorized representatives is subject to Sanctions, or is located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction, or is owned or controlled, directly or indirectly, by any person that is subject to Sanctions or that is located in, ordinarily resident in, or organized under the laws of, any Embargoed Jurisdiction. You further covenant that the foregoing shall be true during the entire period of this agreement. </p>
    
    <p><br>
    </p>
    
    <p>(e) If you access or use the Service outside the United States, you are solely responsible for ensuring that your access and use of the Service in such country, territory or jurisdiction does not violate any applicable laws.</p>
    
    <p><br>
    </p>
    
    <p>(f) You must not use any software or networking techniques, including use of a Virtual Private Network (VPN) to modify your internet protocol address or otherwise circumvent or attempt to circumvent this prohibition. We reserve the right, but have no obligation, to monitor where our Services are accessed from. Furthermore, we reserve the right, at any time, in our sole discretion, to block access to the Service, in whole or in part, from any geographic location, IP addresses and unique device identifiers or to any user who we believe is in breach of these Terms.</p>
    
    <p><br>
    </p>
    
    <p>(g) You may not access or utilize Artzero and/or Services for the purpose of web crawling, web harvesting, data mining, data extraction, scraping or aggregating information, including without limitation listings and smart contracts available on or through Artzero.io and/or Services, or similar activities without our prior written consent in our sole discretion. Users who wish to engage in any of the foregoing activities must contact us at <a href="http://www.artzero.io/contact-us">www.Artzero.io/contact-us</a> to obtain our prior approval and an application programming interface (the “API”) to legally access our servers. Upon approval we will issue the API. Failure to respond constitutes disapproval. We reserve the right to implement testing and maintenance of the API at our sole discretion. Engaging in any of the activities referenced in the first sentence of this paragraph without prior authorization is a prohibited material breach of these Terms of Service and may subject violators to legal liability. </p>
    
    <p><br>
    </p>
    
    <p>(h) You are strictly prohibited to carry out any behaviour that disrupts, suspends, slows or prevents the continuity of the Service; any intrusion or attempted intrusion into Artzero’s information systems; any action placing a disproportionate load on ArtZero’s digital infrastructures; any infringement of the security and authentication measures; any act infringing ArtZero’s rights and financial interests, whether commercial or legal.</p>
    
    <p><br>
    </p>
    
    <p>(i) Encourage or enable any other individual to do any of the foregoing. </p>
    
    <p><br>
    </p>
    
    <p>ArtZero is not obligated to monitor access to or use of the Service or to review or edit any content. However, we have the right to do so for the purpose of operating the Service, to ensure compliance with these Terms of Service and to comply with applicable law or other legal requirements. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</p>
    
    <p><br>
     </p>
    
    <p><strong>5. User Content</strong></p>
    
    <p>Our Services may allow you to store or share content such as text (in posts or communications with others), files, documents, graphics, images, music, software, audio and video. Anything (other than Feedback) that you post or otherwise make available through the Services is referred to as “<strong>User Content</strong>”. User Content may include the NFT Content. </p>
    
    <p><br>
    </p>
    
    <p>You represent and warrant that you own or otherwise control all of the rights to the content that you post or that you otherwise provide on or through the website; that, as at the date that the content or material is submitted to Artzero.io: (i) the content and material is accurate; (ii) use of the content and material you supply does not breach any applicable Artzero.io policies or guidelines and will not cause injury to any person or entity (including that the content or material is not defamatory); (iii) the content is lawful. You agree to indemnify Artzero and its affiliates for all claims brought by a third party against it or its affiliates arising out of or in connection with a breach of any of these warranties.</p>
    
    <p><br>
    </p>
    
    <p>ArtZero does not claim any ownership rights in any User Content and nothing in these Terms will be deemed to restrict any rights that you may have to your User Content. </p>
    
    <p><br>
    </p>
    
    <p>You can remove certain of your User Content by specifically deleting it. You should know that in certain instances, some of your User Content (such as posts or comments you make, or your NFT Content) may not be completely removed and copies of your User Content may continue to exist on the Service or NFT. To the maximum extent permitted by law, we are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any of your User Content. </p>
    
    <p><br>
    </p>
    
    <p>By using the Service, you agree not to:</p>
    
    <p><br>
    </p>
    
    <p>(a) Infringe, misappropriate or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation. You are solely responsible for all your User Content. You represent and warrant that you have (and will have) all rights that are necessary to grant us the license rights in your User Content under these Terms of Service.</p>
    
    <p><br>
    </p>
    
    <p>(b) Post, upload, publish, submit or transmit any illicit content, including but not limited to: content that is fraudulent, false, misleading or deceptive; is defamatory, obscene, pornographic, vulgar or offensive; promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; violent or threatening or promotes violence or actions that are threatening to any person or entity; or promotes illegal or harmful activities or substances; </p>
    
    <p><br>
    </p>
    
    <p>(c) Use, display, mirror or frame the Service or any individual element within the Service, ArtZero’s name, any ArtZero trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without ArtZero’s express written consent; </p>
    
    <p><br>
    </p>
    
    <p>(d) Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation; </p>
    
    <p><br>
    </p>
    
    <p>(e) Encourage or enable any other individual to do any of the foregoing. </p>
    
    <p><br>
    </p>
    
    <p>We reserve the right, but are not obligated, to remove or disable access to any content, including User Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider it objectionable or in violation of these Terms of Service. We have the right to investigate violations of these Terms of Service or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law. </p>
    
    <p><br>
    </p>
    
    <p>The sale of stolen assets, assets taken without authorization, and otherwise illegally obtained assets on the Service is prohibited. If you have reason to believe that an asset listed on the Service was illegally obtained, please contact us immediately. Listing illegally obtained assets may result in your listings being canceled, your assets being hidden, or you being suspended from the Services. </p>
    
    <p><br>
    </p>
    
    <p>Because Artzero.io facilitates a lot of products for sale offered by creators and collectors on the website, it is not possible for us to be aware of the contents of each NFT or collection listed for sale, or each comment or review that is displayed. Accordingly, Artzero.io operates on a "notice and takedown" basis. If you believe that any content on the platform is against the Terms, please notify us immediately at <a href="https://artzero.io/contact-us">https://artzero.io/contact-us</a>. We will make all reasonable endeavours within a reasonable time.</p>
    
    <p><br>
    </p>
    
    <p>Artzero.io reserves the right to refuse access to the website, terminate accounts, remove or edit content at any time without notice to you.</p>
    
    <p><br>
     </p>
    
    <p><strong>6. ArtZero’s license for User Content</strong></p>
    
    <p>If you do post content or submit material, and unless we indicate otherwise, you</p>
    
    <p><br>
    </p>
    
    <p>(a) grant Artzero and its affiliates a non-exclusive, royalty-free, irrevocable, perpetual and fully sublicensable rights to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media; and</p>
    
    <p><br>
    </p>
    
    <p>(b) Artzero and its affiliates and sublicensees the right to use the name that you submit in connection with such content, if they choose.</p>
    
    <p><br>
    </p>
    
    <p>You agree that the rights you grant above are irrevocable during the entire period of protection of your intellectual property rights associated with such content and material. You agree to waive your right to be identified as the author of such content and your right to object to derogatory treatment of such content. You agree to perform all further acts necessary to perfect any of the above rights granted by you to Artzero, including the execution of deeds and documents, at its request.</p>
    
    <p><br>
     </p>
    
    <p><strong>7. Interruptions</strong></p>
    
    <p>Your access and use of the Service may be interrupted from time to time for any of several reasons, including without limitation, the event of force majeure or unforeseeable and unavoidable behavior on the part of a third party, the malfunction of equipment, periodic updating, maintenance, introduction of new facilities and service, repair of the Service or other actions that ArtZero, in its sole discretion, may elect to take. Due to the specific nature of the Internet and telecommunications networks, ArtZero cannot guarantee the continuous availability of the Service.</p>
    
    <p><br>
     </p>
    
    <p><strong>8. Privacy</strong></p>
    
    <p>Please review our Privacy Notice, which also governs your visit to Artzero.io, to understand our practices. The personal information / data provided to us by you during the course of usage of Artzero.io will be treated as strictly confidential and in accordance with the Privacy Notice and applicable laws and regulations. If you object to your information being collected, transferred, used, or shared, please do not use the website.</p>
    
    <p><br>
     </p>
    
    <p><strong>9. Disclaimer</strong></p>
    
    <p>ArtZero operates the platform including marketplace and launchpad, which is a peer-to-peer online service allowing users to discover and directly interact with each other and NFTs available on Aleph Zero blockchain. ArtZero is not a wallet provider, exchange, broker, financial institution, money services business, or creditor.</p>
    
    <p><br>
    </p>
    
    <p>You agree, understand and acknowledge that the website is an online administrative platform only, which is an interface to interact with the Protocols and Blockchains. ArtZero does not provide the Protocol. Our Services also allows users to create and deploy NFTs. ArtZero does not provide the Protocol, is not a and cannot be a party, and do not have custody to or control in any manner any transactions on the website. </p>
    
    <p><br>
    </p>
    
    <p>You bear full responsibility for verifying the identity, legitimacy, and authenticity of NFTs and any content associated with such NFTs, which you purchase on the ArtZero platform, including on the marketplace and launchpad. ArtZero makes no claims about the Identity, legitimacy, or authenticity of NFTs on the platform.</p>
    
    <p><br>
     </p>
    
    <p><strong>10. Licence for website access</strong></p>
    
    <p>Subject to your compliance with these Terms of Service and payment of applicable fees, if any, Artzero grants you a limited licence to access and make personal use of this website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Artzero and / or its affiliates, as may be applicable. This licence does not include any resale or commercial use of this website or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this website or its contents; any downloading or copying of account information for the benefit of another seller; or any use of data mining, robots, or similar data gathering and extraction tools.</p>
    
    <p><br>
    </p>
    
    <p>This website or any portion of this website (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of Artzero, as may be applicable.</p>
    
    <p><br>
    </p>
    
    <p>You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Artzero.io and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilising Artzero or its affiliates' names or trademarks without the express written consent of Artzero and / or its affiliates, as applicable. Any unauthorised use terminates the permission or license granted by Artzero, as applicable.</p>
    
    <p><br>
    </p>
    
    <p>You are granted a limited, revocable, and non-exclusive right to create a hyperlink to the Welcome page of Artzero.io as long as the link does not portray Artzero , Artzero.io, their affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Artzero.io logo or other proprietary graphic or trademark as part of the link without express written consent of Artzero and, as may be applicable.</p>
    
    <p><br>
     </p>
    
    <p><strong>11. Copyright, authors' rights and database rights</strong></p>
    
    <p>The Service, including its “look and feel”, such as text, graphics, logos, button icons, images,…; audio clips, digital downloads, data compilations, and software, proprietary content, information and other materials, and all content and other materials contained therein, including, without limitation, is the property of Artzero, or our affiliates, licensors, or users, as applicable, and you agree not to take any action(s) inconsistent with such ownership interests. We and our affiliates, licensors, and users, as applicable, reserve all rights in connection with the Service and its content, including, without limitation, the exclusive right to create derivative works.</p>
    
    <p><br>
    </p>
    
    <p>ArtZero’s name, logo, and other marks indicated on our website are trademarks or registered trademarks of Artzero in the European Union and/or other jurisdictions. Artzero's graphics, logos, page headers, button icons, scripts and service names are the trademarks or trade dress of Artzero. Artzero's trademarks and trade dress may not be used in connection with any product or service that is not Artzero's, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Artzero. All other trademarks not owned by Artzero that appear on this website are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Artzero. trademarks, and any ArtZero product or service names, designs, logos, and slogans are the intellectual property of ArtZero or our affiliates or licensors and may not be copied, imitated or used, in whole or in part, without our prior written permission in each instance. You may not use any metatags or other “hidden text” utilizing “ArtZero” or any other name, trademark or product or service name of ArtZero or our affiliates or licensors without our prior written permission. In addition, the “look and feel” of the Service constitutes the service mark, trademark or trade dress of ArtZero and may not be copied, imitated or used, in whole or in part, without our prior written permission.</p>
    
    <p><br>
    </p>
    
    <p>All other third-party trademarks, registered trademarks, and product names mentioned on the Service or contained in the content linked to or associated with any NFTs displayed on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable intellectual property rights holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship, or recommendation by ArtZero.</p>
    
    <p><br>
    </p>
    
    <p><a name="_heading=h.gjdgxs"></a>We welcome feedback, comments, and suggestions for improvements to the Service (“Feedback”). You acknowledge and expressly agree that any contribution of Feedback does not and will not give or grant you any right, title, or interest in the Service or in any such Feedback. You agree that ArtZero may use and disclose Feedback in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim. You hereby assign to ArtZero any and all right, title, and interest (including, but not limited to, any patent, copyright, trade secret, trademark, show-how, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback.</p>
    
     `,
  },
  {
    label: "Privacy Policy",
    content: `<p>ArtZero (“ArtZero,” “we”, “us”, or “our”) is committed to protecting your privacy. ArtZero operates a digital Marketplace which is a peer-to-peer online service allowing Collectors to acquire NFTs from Creators and other Collectors. ArtZero acts solely as an intermediary, offering a digital infrastructure in order to facilitate transactions on NFTs. </p>
    <p><br></p>
    <p>The purpose of this document is to provide information regarding the processing of Personal Data (as defined below) we collect, use, and share in connection with the ArtZero website, mobile app, and other software provided on or in connection with our services, as described in our Terms of Service (collectively, the “Service”) by ArtZero. “NFT” in this Privacy Policy means a non-fungible token or similar digital item implemented on Aleph Zero blockchain, which uses smart contracts to link to or otherwise be associated with certain content or data.</p>
      <p><br></p>
      <p>The purpose of this document is to provide information regarding the processing of personal data by ArtZero. </p>
      
      <ol start="1" type="1"> 
      <li>Types of Data We Collect. “Personal Data” means data that allows someone to identify you individually, including, for example, your name, email address, as well as any other non-public information about you that is associated with or linked to any of the foregoing. “Anonymous Data” means data, including aggregated and de-identified data, that is not associated with or linked to your Personal Data; Anonymous Data does not, by itself, permit the identification of individual persons. We collect Personal Data and Anonymous Data as described below.</li>
       <ol start="1" type="a">
       <li> &nbsp Information You Provide Us.</li>
       <ol start="1" type="I"> <li>When you use our Service, update your account profile, or contact us, we may collect Personal Data from you, such as email address, first and last name, user name, and other information you provide. We also collect your blockchain address, which may become associated with Personal Data when you use our Service.</li>
       <li>Our Service lets you store preferences like how your content is displayed, notification settings, and favorites. We may associate these choices with your ID, browser, or mobile device.</li>
       <li>If you provide us with feedback or contact us, we will collect your name and contact information, as well as any other content included in the message.</li>
       <li>We may also collect Personal Data at other points in our Service where you voluntarily provide it or where we state that Personal Data is being collected.<br>
       <br>
       </li>
       </ol> <li>Information Collected via Technology. As you navigate through and interact with our Service, we may use automatic data collection technologies to collect certain information about your equipment, browsing actions, and patterns, including:</li>
       <ol start="1" type="I"> <li>Information Collected by Our Servers. To provide our Service and make it more useful to you, we (or a third party service provider) collect information from you, including, but not limited to, your browser type, operating system, Internet Protocol (“IP”) address, mobile device ID, blockchain address, wallet type, and date/time stamps.</li>
       <li>Log Files. As is true of most websites and applications, we gather certain information automatically and store it in log files. This information includes IP addresses, browser type, Internet service provider (“ISP”), referring/exit pages, operating system, date/time stamps, and clickstream data. We use this information to analyze trends, administer the Service, track users’ movements around the Service, and better tailor our Services to our users’ needs. For example, some of the information may be collected so that when you visit the Service, it will recognize you and the information can be used to personalize your experience.</li>
       <li>Cookies. Like many online services, we use cookies to collect information. We may use both session Cookies (which expire once you close your web browser) and persistent Cookies (which stay on your computer until you delete them) to analyze how users interact with our Service, make improvements to our product quality, and provide users with a more personalized experience.</li>
       <li>Pixel Tag. In addition, we use “Pixel Tags” (also referred to as clear Gifs, Web beacons, or Web bugs). Pixel Tags allow us to analyze how users find our Service, make the Service more useful to you, and tailor your experience with us to meet your particular interests and needs.</li>
       <li>How We Respond to Do Not Track Signals. Our systems do not currently recognize “do not track” signals or other mechanisms that might enable Users to opt out of tracking on our site.</li>
       <li>Analytics Services. In addition to the tracking technologies we place like Cookies and Pixel Tags, other companies may set their own cookies or similar tools when you visit our Service. This includes third-party analytics services (“Analytics Services”) that we engage to help analyze how users use the Service. The information generated by the Cookies or other technologies about your use of our Service (the “Analytics Information”) is transmitted to the Analytics Services. The Analytics Services use Analytics Information to compile reports on user activity, which we may receive on an individual or aggregate basis. We use the information we get from Analytics Services to improve our Service. The Analytics Services may also transfer information to third parties where required to do so by law, or where such third parties process Analytics Information on their behalf. Each Analytics Services’ ability to use and share Analytics Information is restricted by such Analytics Services’ terms of use and privacy policy. By using our Service, you consent to the processing of data about you by Analytics Services in the manner and for the purposes set out above.</li>
       </ol> </ol> </ol><ol start="1" type="1"> <ol start="3" type="a"> <li>Information Collected from Third-Party Companies. We may receive Personal and/or Anonymous Data about you from companies that offer their products and/or services for use in conjunction with our Service or whose products and/or services may be linked from our Service. For example, third-party wallet providers provide us with your blockchain address and certain other information you choose to share with those wallets providers. We may add this to the data we have already collected from or about you through our Service.<br>
       <br>
       </li>
       <li>Public Information Observed from Blockchains. We collect data from activity that is publicly visible and/or accessible on blockchains. This may include blockchain addresses and information regarding purchases, sales, or transfers of NFTs, which may then be associated with other data you have provided to us.<br>
       <br>
       </li>
       </ol> <li>Use of Your Personal Data.</li>
       <ol start="1" type="a"> <li>We process your Personal Data to run our business, provide the Service, personalize your experience on the Service, and improve the Service. Specifically, we use your Personal Data to:</li>
       <ol start="1" type="I"> <li>facilitate the creation of and secure your account;</li>
       <li>identify you as a user in our system;</li>
       <li>provide you with our Service, including, but not limited to, helping you view, explore, and create NFTs using our tools and, at your own discretion, connect directly with others to purchase, sell, or transfer NFTs on public blockchains;</li>
       <li>improve the administration of our Service and quality of experience when you interact with our Service, including, but not limited to, by analyzing how you and other users find and interact with the Service;</li>
       <li>provide customer support and respond to your requests and inquiries;</li>
       <li>investigate and address conduct that may violate our Terms of Service;</li>
       <li>detect, prevent, and address fraud, violations of our terms or policies, and/or other harmful or unlawful activity;</li>
       <li>display your username next to the NFTs currently or previously accessible in your third-party wallet, and next to NFTs on which you have interacted;</li>
       <li>send you a welcome email to verify ownership of the email address provided when your account was created;</li>
       <li>send you administrative notifications, such as security, support, and maintenance advisories;</li>
       <li>send you notifications related to actions on the Service, including notifications of offers on your NFTs;</li>
       <li>send you newsletters, promotional materials, and other notices related to our Services or third parties' goods and services;</li>
       <li>respond to your inquiries related to employment opportunities or other requests;</li>
       <li>comply with applicable laws, cooperate with investigations by law enforcement or other authorities of suspected violations of law, and/or to pursue or defend against legal threats and/or claims; and</li>
       <li>act in any other way we may describe when you provide the Personal Data.</li>
       </ol> <li>We may create Anonymous Data records from Personal Data. We use this Anonymous Data to analyze request and usage patterns so that we may improve our Services and enhance Service navigation. We reserve the right to use Anonymous Data for any purpose and to disclose Anonymous Data to third parties without restriction.</li>
       </ol> </ol><p><a name="_heading=h.gjdgxs"></a></p>
      
       <ol start="3" type="1"> <li>Disclosure of Your Personal Data. We disclose your Personal Data as described below and as described elsewhere in this Privacy Policy.</li>
       <ol start="1" type="a"> <li>Third Party Service Providers. We may share your Personal Data with third party service providers to: provide technical infrastructure services; conduct quality assurance testing; analyze how our Service is used; prevent, detect, and respond to unauthorized activities; provide technical and customer support; and/or to provide other support to us and to the Service.</li>
       <li>Affiliates. We may share some or all of your Personal Data with any subsidiaries, joint ventures, or other companies under our common control (“Affiliates”), in which case we will require our Affiliates to honor this Privacy Policy.</li>
       <li>Corporate Restructuring. We may share some or all of your Personal Data in connection with or during negotiation of any merger, financing, acquisition, or dissolution transaction or proceeding involving sale, transfer, divestiture, or disclosure of all or a portion of our business or assets. In the event of an insolvency, bankruptcy, or receivership, Personal Data may also be transferred as a business asset. If another company acquires our company, business, or assets, that company will possess the Personal Data collected by us and will assume the rights and obligations regarding your Personal Data as described in this Privacy Policy.</li>
       <li>Legal Rights. Regardless of any choices you make regarding your Personal Data (as described below), ArtZero may disclose Personal Data if it believes in good faith that such disclosure is necessary: (a) in connection with any legal investigation; (b) to comply with relevant laws or to respond to subpoenas, warrants, or other legal process served on ArtZero; (c) to protect or defend the rights or property of ArtZero or users of the Service; and/or (d) to investigate or assist in preventing any violation or potential violation of the law, this Privacy Policy, or our Terms of Service.</li>
       <li>Other Disclosures. We may also disclose your Personal Data: to fulfill the purpose for which you provide it; for any other purpose disclosed by us when you provide it; or with your consent.</li>
       </ol> <li>Third-Party Websites. Our Service may contain links to third-party websites. When you click on a link to any other website or location, you will leave our Service and go to another site, and another entity may collect Personal Data from you. We have no control over, do not review, and cannot be responsible for these third-party websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these third-party websites or their content, or to any collection of your Personal Data after you click on links to such third-party websites. We encourage you to read the privacy policies of every website you visit. Any links to third-party websites or locations are for your convenience and do not signify our endorsement of such third parties or their products, content, or websites.</li>
       <li>Third-Party Wallets. To use our Service, you must use a third-party wallet which allows you to engage in transactions on public blockchains. Your interactions with any third-party wallet provider are governed by the applicable terms of service and privacy policy of that third party.</li>
       <li>Your Choices Regarding Information. You have several choices regarding the use of information on our Services:</li>
       <ol start="1" type="a"> <li>Email Communications. We may periodically send you newsletters and/or emails that directly promote the use of our Service or third parties’ goods and services. When you receive newsletters or promotional communications from us, you may indicate a preference to stop receiving these communications from us by following the unsubscribe instructions provided in the email you receive or through the Notifications preferences in your Settings page. Despite these preferences, we may send you occasional transactional service-related informational communications.<br>
       <br>
       </li>
       <li>If you decide at any time that you no longer wish to accept Cookies from our Service for any of the purposes described above, then you can instruct your browser, by changing its settings, to stop accepting Cookies or to prompt you before accepting a Cookie from the websites you visit. Consult your browser’s technical information. If you do not accept Cookies, however, you may not be able to use all portions of the Service or all functionality of the Service.</li>
       </ol> <li>Data Access and Control. You can view, access, edit, or delete your Personal Data for certain aspects of the Service via your Settings page. You may also have certain additional rights:</li>
       <ol start="1" type="a"> <li>If you are a user in the European Economic Area or United Kingdom, you have certain rights under the respective European and UK General Data Protection Regulations (“GDPR”). These include the right to (i) request access and obtain a copy of your personal data; (ii) request rectification or erasure; (iii) object to or restrict the processing of your personal data; and (iv) request portability of your personal data. Additionally, if we have collected and processed your personal data with your consent, you have the right to withdraw your consent at any time.<br>
       <br>
       </li>
       <li>If you are a California resident, you have certain rights under the California Consumer Privacy Act (“CCPA”). These include the right to (i) request access to, details regarding, and a copy of the personal information we have collected about you and/or shared with third parties; (ii) request deletion of the personal information that we have collected about you; and (iii) the right to opt-out of sale of your personal information. As the terms are defined under the CCPA, we do not “sell” your “personal information.”</li>
       <li>If you wish to exercise your rights under the GDPR, CCPA, or other applicable data protection or privacy laws, please contact us by sending an email with title “Submit a request” to <a href="mailto:support@artzero.io">support@artzero.io</a>, specify your request, and reference the applicable law. We may ask you to verify your identity, or ask for more information about your request. We will consider and act upon any above request in accordance with applicable law. We will not discriminate against you for exercising any of these rights.<br>
       <br>
       </li>
       <li>Notwithstanding the above, we cannot edit or delete any information that is stored on Aleph Zero blockchain, or any other blockchains, as we do not have custody or control over any blockchains. The information stored on the blockchain may include purchases, sales, and transfers related to your blockchain address and NFTs held at that address.</li>
       </ol> <li><a name="_heading=h.gjdgxs"></a>Data Retention. We may retain your Personal Data as long as you continue to use the Service, have an account with us, or for as long as is necessary to fulfill the purposes outlined in this Privacy Policy. We may continue to retain your Personal Data even after you deactivate your account and/or cease to use the Service if such retention is reasonably necessary to comply with our legal obligations, to resolve disputes, prevent fraud and abuse, enforce our Terms or other agreements, and/or protect our legitimate interests. Where your Personal Data is no longer required for these purposes, we will delete it.<br>
       <br>
       </li>
       <li>Data Protection. We care about the security of your information and use physical, administrative, and technological safeguards to preserve the integrity and security of information collected through our Service. However, no security system is impenetrable and we cannot guarantee the security of our systems. In the event that any information under our custody and control is compromised as a result of a breach of security, we will take steps to investigate and remediate the situation and, in accordance with applicable laws and regulations, notify those individuals whose information may have been compromised.</li>
       <ol start="1" type="a"> <li>You are responsible for the security of your digital wallet, and we urge you to take steps to ensure it is and remains secure. If you discover an issue related to your wallet, please contact your wallet provider.<br>
       <br>
       </li>
       </ol> <li>Minors. We do not intentionally gather Personal Data from visitors who are under the age of 13. Our Terms of Service require all users to be at least 18 years old. Minors who are at least 13 years old but are under 18 years old may use a parent or guardian’s ArtZero account, but only with the involvement of the account holder. If a child under 13 submits Personal Data to ArtZero and we learn that the Personal Data is the information of a child under 13, we will attempt to delete the information as soon as possible. If you believe that we might have any Personal Data from a child under 13, please contact us by sending an email with the title “Submit a request” to <a href="mailto:support@artzero.io">support@artzero.io</a>.<br>
       <br>
       </li>
       <li>Users Outside of the United States. If you are a non-U.S. user of the Service, by visiting the Service and providing us with data, you acknowledge and agree that your Personal Data may be processed for the purposes identified in the Privacy Policy. In addition, your Personal Data may be processed in the country in which it was collected and in other countries, including the United States, where laws regarding processing of Personal Data may be less stringent than the laws in your country. By providing your Personal Data, you consent to such transfer.</li>
       <li>Changes to This Privacy Policy. This Privacy Policy may be updated from time to time for any reason. We will notify you of any changes to our Privacy Policy by posting the new Privacy Policy at <a href="https://opensea.io/privacy">https://ArtZero.io/privacy</a>. The date the Privacy Policy was last revised is identified at the beginning of this Privacy Policy. You are responsible for periodically visiting our Service and this Privacy Policy to check for any changes.</li>
       <li>Questions; Contacting ArtZero; Reporting Violations. If you have any questions or concerns or complaints about our Privacy Policy or our data collection or processing practices, or if you want to report any security violations to us, please contact us by sending an email with the title “Submit a request” to <a href="mailto:support@artzero.io">support@artzero.io</a>.</li>
       </ol>`,
  },
  {
    label: "Cookies Policy",
    content: `<p><a name="_heading=h.gjdgxs"></a>ArtZero (“ArtZero,” “we”, “us”, “Website”, or “our”) uses cookies To enable Users to benefit from the Services offered by the Website https://ArtZero.io/ such as its consultation, optimization of its use or personalization according to the Users.</p>

    <p><br>
    </p>
    
    <p>ArtZero operates a digital Marketplace which is a peer-to-peer online service allowing Collectors to acquire NFTs from Creators and other Collectors. ArtZero acts solely as an intermediary, offering a digital infrastructure in order to facilitate transactions on NFTs.</p>
    
    <p><br>
    </p>
    
    <p>The purpose of this document is to provide information regarding the processing of using Cookies placed on your browser relating to the navigation of your terminal (computer, tablet, smartphone, etc.) on the Website. Cookies will be used to recognize your browser for the duration of the cookie's validity and return certain information to the Website (such as a session identifier or language choice). </p>
    
    <p><br>
    </p>
    
    <p>Only the sender of a cookie can read or modify the information contained in it. </p>
    
    <p><br>
    </p>
    
    <p>Different types of cookies: </p>
    
    <p>- session cookies that disappear as soon as you leave the Website; </p>
    
    <p>- permanent cookies that remain on your terminal until their lifetime expires or until you delete them using your browser's functions. </p>
    
    <p><br>
    </p>
    
    <p>You are informed that, during your visits to the Website, cookies may be placed on your terminal equipment. </p>
    
    <p><br>
    </p>
    
    <p>Some cookies are essential to the use of the Website: these are technical cookies used by the Website host for the technical management of the network.</p>
    
    <p><br>
    </p>
    
    <p>Others are used to analyze the frequentation and the use made of the Website, in order: </p>
    
    <p>- to make it evolve in the sense of an improvement of the experience of navigation, in the final objective to propose you a Website always more adapted; to conduct studies; </p>
    
    <p>- to memorize your browser's display preferences (language used, display parameters, operating system used, etc.) and to adapt the presentation of the Website to the time of your visits, according to the hardware and software of visualization or reading that your terminal equipment includes and which are used for navigation on our Website; </p>
    
    <p>- to implement security measures. </p>
    
    <p><br>
    </p>
    
    <p>Cookies used on our Website are: </p>
    
    <p>- ArtZero’s cookies ; </p>
    
    <p>- third party cookies chosen by ARTZERO Company in order to achieve certain objectives</p>
    
    <p><br>
    </p>
    
    <p>The placement and use of cookies by these companies is subject to their own terms of use, which you can view on their respective websites. </p>
    
    <p><br>
    </p>
    
    <p>If your terminal is used by several persons, and when a single terminal has multiple browsers, we cannot be certain that the services and advertisements directed to your terminal equipment correspond to your own use of that terminal equipment and not to that of another User of that terminal equipment. </p>
    
    <p><br>
    </p>
    
    <p>Sharing with others the use of your terminal equipment and configuring your browser settings with respect to cookies is your free choice and responsibility. </p>
    
    <p><br>
    </p>
    
    <p>When you first visit our Website, you will be asked to accept, configure or refuse the use of some cookies. </p>
    
    <p><br>
    </p>
    
    <p>If you do not want cookies to be placed or read on your terminal equipment, a refusal cookie will be placed on your equipment so that ARTZERO can record the information according to which you have refused the use of cookies. If you delete this refusal cookie, it will no longer be possible to identify you as having refused the use of cookies. </p>
    
    <p><br>
    </p>
    
    <p>Also, when you accept the deposit of cookies, a consent cookie is placed. </p>
    
    <p><br>
    </p>
    
    <p>Refusal or consent cookies must remain on your terminal equipment. You can change your choices at any time by clicking here. </p>
    
    <p><br>
    </p>
    
    <p>You can manage and modify the use of cookies at any time according to the possibilities listed below: </p>
    
    <p>- directly on our Website, in the module provided for this purpose, by clicking here, or </p>
    
    <p>- from your browser, or </p>
    
    <p>- from interprofessional opposition platforms.</p>
    
    <p><br>
    </p>
    
    <p><strong>Please note your refusal to place a cookie is based on the deposit of a cookie. Therefore, if you deactivate all cookies on your terminal or if you change your terminal, we will no longer know that you have chosen this option. </strong></p>
    
    <p><strong><br>
    </strong></p>
    
    <p>Several advertising professionals' platforms also offer you the possibility to refuse or accept cookies used by the member companies. These centralized mechanisms do not block the display of advertisements but only prevent the installation of cookies that allow the adaptation of advertisements to your interests and behavior. </p>
    
    <p><br>
    </p>
    
    <p>Within the framework of the use of cookies as described on the present page, the ARTZERO Company is likely to process Personal Data concerning you, such as IP addresses, in its capacity as data controller. </p>
    
    <p><br>
    </p>
    
    <p>Third-party cookies on the Website are set by external processors, which are likely, if you accept these cookies, to process Personal Data about you. </p>
    
    <p><br>
    </p>
    
    <p>The issuance and use of these cookies by third parties is subject to their own privacy policies. For more information about these processes, you can refer to their privacy policies. </p>
    
    <p><br>
    </p>
    
    <p>The data collected is essential to achieve the objectives pursued by each cookie. It is only intended for the authorized departments of ArtZero and/or the Company issuing the third-party cookies. </p>
    
    <p><br>
    </p>
    
    <p>Personal Data about you may be transmitted to service providers located in third countries outside the European Union. </p>
    
    <p><br>
    </p>
    
    <p>These data transfers are governed by a cross-border flow agreement established in accordance with the contractual clauses issued by the European Commission and currently in force. </p>
    
    <p><br>
    </p>
    
    <p>Personal Data collected via cookies is never kept longer than necessary to achieve the purpose of the cookie and, in any case, not more than 13 months. </p>
    
    <p><br>
    </p>
    
    <p><a name="_heading=h.gjdgxs"></a> </p>
    
    <p>For more information, including how to exercise your rights, see our Privacy Policy. </p>
    
    <p><br>
    </p>
    `,
  },
];
