export const AccountActionTypes = {
  SET_ACTIVE_ADDRESS: "SET_ACTIVE_ADDRESS",
  GET_PROFILE: "GET_PROFILE",
  ACCOUNT_LOADING: "ACCOUNT_LOADING",
  ACCOUNT_ERROR: "ACCOUNT_ERROR",
  SET_PROFILE_ATTRIBUTE: "SET_PROFILE_ATTRIBUTE",
};
